### ISSUE TITLE
Lesson card: "balance scales"? Who do?

### ISSUE THREAD

**Issue by Perluto** [Perluto/Measurement#1]
Thiết kế class rack, scene, block, scales.
Class rack: chức năng: nơi chứa các quả cân (block);
Class block: là quả cân có cân nặng, vị trí, khả năng di chuyển ( = kéo chuột), đặt vào các rack.
Class scales: chức năng : thệ hiện độ cân bằng của 2 bên rack trái phải của cái cân.

**Comment by Perluto** [comment]
t đảm nhiệm nhe!

**Comment by BotLineTia** [comment]
Oke luôn Hoàng làm nhé

**Comment by Perluto** [comment]
Cơ bản đã xong, xong phần thô với commit first commit. 
Còn 1 số vấn đề nên tôi sẽ tạo thêm các issue để ae giải quyết.
