### ISSUE TITLE
Hiện màu khi đưa quả cân vào giá hoặc đưa quả cân về (chi tiết trong comment)

### ISSUE THREAD

**Issue by BotLineTia** [Perluto/Measurement#11]

**Comment by BotLineTia** [comment]
Đưa quả cân vào giá , giá sáng hoặc tô màu gì đó để nhận biết quả cân đã được đặt vào

**Comment by Perluto** [comment]
Done: https://github.com/Perluto/Measurement/commit/6c8d26fb4f8e9a1ece42d5e35f82c8552622a37c
https://github.com/Perluto/Measurement/commit/78964cb52c88cc1a932ecaab97267cec2d0d7f83
